options:
  san-ip:
    type: string
    description: "Management IP address of Nimble Storage array/group."
    default:
  san-login:
    type: string
    description: "Nimble Storage account login with minimum power user (admin) privilege if RBAC is used."
    default:
  san-password:
    type: string
    description: "Password of the admin account for nimble array."
    default:
  volume-driver:
    type: string
    description: "Use either 'iscsi' for iSCSI or 'fc' for Fibre Channel."
    default: iscsi
  volume-backend-name:
    type: string
    description: "A volume back-end name which is specified in the cinder.conf file. This is also used while assigning a back-end name to the Nimble volume type."
    default:
  use-multipath-for-image-xfer:
    type: boolean
    description: "Enables or disables the use of multipathing."
    default: True
  encryption:
    type: string
    description: "Used to enable encryption for a volume-type. Either 'yes' or 'no'."
    default:
  performance-policy-name:
    type: string
    description: "The name of a performance policy which exists on the Nimble array and should be enabled for every volume in a volume type."
    default:
  multi-initiator:
    type: boolean
    description: "Used to enable multi-initiator access for a volume-type."
    default: True
  pool-name:
    type: string
    description: "Nimble Controller pool name"
    default: "default"
  subnet-label:
    type: string
    description: "Nimble Subnet Label"
    default: "*"
  verify-cert-path:
    type: string
    description: "Path to Nimble Array SSL certificate"
    default: "None"
  verify-cert:
    type: string
    description: "Whether to verify Nimble SSL Certificate"
    default: "False"
